name: Publish

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Upload built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: |
            index.html
            out.js

  Publish:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout Github pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Delete all files
        run: rm -rf ./*

      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: website

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v5
        with:
          branch: gh-pages
          message: Update website